# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.task_toggle:
            class: AppBundle\Service\TaskManager
            arguments: ['@doctrine.orm.entity_manager']

