# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    app.task_manager:
            class: AppBundle\Service\TaskManager
            arguments: ['@doctrine.orm.entity_manager']

    app.user_manager:
            class: AppBundle\Service\UserManager
            arguments: ['@security.password_encoder', '@doctrine.orm.entity_manager']